//---------------------------------------------------------------------------------------
// this module is auto generated by prbs_verilog_gen.py
// Generated on: 2025-04-22T09:37:40
// Description: Verilog module for PRBS9 generator,this module is 12 times shift result.
// Polynomial: 1 + x^5 + x^9
// Width: 32
// Iterations: 12
//--------------------------------------------------------------------------------------

module prbs9_width32_iter12 (
    input [31:0] din,
    output [31:0] dout
);

    assign dout[0] = din[3] ^ din[6] ^ din[7];
    assign dout[1] = din[4] ^ din[7] ^ din[8];
    assign dout[2] = din[0] ^ din[8];
    assign dout[3] = din[0] ^ din[1] ^ din[5];
    assign dout[4] = din[1] ^ din[2] ^ din[6];
    assign dout[5] = din[2] ^ din[3] ^ din[7];
    assign dout[6] = din[3] ^ din[4] ^ din[8];
    assign dout[7] = din[0] ^ din[4];
    assign dout[8] = din[1] ^ din[5];
    assign dout[9] = din[2] ^ din[6];
    assign dout[10] = din[3] ^ din[7];
    assign dout[11] = din[4] ^ din[8];
    assign dout[12] = din[0];
    assign dout[13] = din[1];
    assign dout[14] = din[2];
    assign dout[15] = din[3];
    assign dout[16] = din[4];
    assign dout[17] = din[5];
    assign dout[18] = din[6];
    assign dout[19] = din[7];
    assign dout[20] = din[8];
    assign dout[21] = din[9];
    assign dout[22] = din[10];
    assign dout[23] = din[11];
    assign dout[24] = din[12];
    assign dout[25] = din[13];
    assign dout[26] = din[14];
    assign dout[27] = din[15];
    assign dout[28] = din[16];
    assign dout[29] = din[17];
    assign dout[30] = din[18];
    assign dout[31] = din[19];

endmodule