//---------------------------------------------------------------------------------------
// this module is auto generated by prbs_verilog_gen.py
// Generated on: 2025-04-22T09:37:43
// Description: Verilog module for PRBS31 generator,this module is 20 times shift result.
// Polynomial: 1 + x^28 + x^31
// Width: 32
// Iterations: 20
//--------------------------------------------------------------------------------------

module prbs31_width32_iter20 (
    input [31:0] din,
    output [31:0] dout
);

    assign dout[0] = din[8] ^ din[11];
    assign dout[1] = din[9] ^ din[12];
    assign dout[2] = din[10] ^ din[13];
    assign dout[3] = din[11] ^ din[14];
    assign dout[4] = din[12] ^ din[15];
    assign dout[5] = din[13] ^ din[16];
    assign dout[6] = din[14] ^ din[17];
    assign dout[7] = din[15] ^ din[18];
    assign dout[8] = din[16] ^ din[19];
    assign dout[9] = din[17] ^ din[20];
    assign dout[10] = din[18] ^ din[21];
    assign dout[11] = din[19] ^ din[22];
    assign dout[12] = din[20] ^ din[23];
    assign dout[13] = din[21] ^ din[24];
    assign dout[14] = din[22] ^ din[25];
    assign dout[15] = din[23] ^ din[26];
    assign dout[16] = din[24] ^ din[27];
    assign dout[17] = din[25] ^ din[28];
    assign dout[18] = din[26] ^ din[29];
    assign dout[19] = din[27] ^ din[30];
    assign dout[20] = din[0];
    assign dout[21] = din[1];
    assign dout[22] = din[2];
    assign dout[23] = din[3];
    assign dout[24] = din[4];
    assign dout[25] = din[5];
    assign dout[26] = din[6];
    assign dout[27] = din[7];
    assign dout[28] = din[8];
    assign dout[29] = din[9];
    assign dout[30] = din[10];
    assign dout[31] = din[11];

endmodule