//---------------------------------------------------------------------------------------
// this module is auto generated by prbs_verilog_gen.py
// Generated on: 2025-04-22T09:37:42
// Description: Verilog module for PRBS23 generator,this module is 20 times shift result.
// Polynomial: 1 + x^2 + x^5 + x^8 + x^16 + x^21 + x^23
// Width: 32
// Iterations: 20
//--------------------------------------------------------------------------------------

module prbs23_width32_iter20_seed1 (
    input [31:0] din,
    output [31:0] dout
);

    assign dout[0] = din[0] ^ din[1] ^ din[2] ^ din[3] ^ din[6] ^ din[11] ^ din[12] ^ din[14] ^ din[17] ^ din[20];
    assign dout[1] = din[1] ^ din[2] ^ din[3] ^ din[4] ^ din[7] ^ din[12] ^ din[13] ^ din[15] ^ din[18] ^ din[21];
    assign dout[2] = din[2] ^ din[3] ^ din[4] ^ din[5] ^ din[8] ^ din[13] ^ din[14] ^ din[16] ^ din[19] ^ din[22];
    assign dout[3] = din[0] ^ din[2] ^ din[3] ^ din[4] ^ din[6] ^ din[8] ^ din[9] ^ din[14] ^ din[15] ^ din[16] ^ din[17] ^ din[20] ^ din[21];
    assign dout[4] = din[1] ^ din[3] ^ din[4] ^ din[5] ^ din[7] ^ din[9] ^ din[10] ^ din[15] ^ din[16] ^ din[17] ^ din[18] ^ din[21] ^ din[22];
    assign dout[5] = din[0] ^ din[4] ^ din[6] ^ din[10] ^ din[11] ^ din[17] ^ din[18] ^ din[19] ^ din[21] ^ din[22];
    assign dout[6] = din[0] ^ din[1] ^ din[2] ^ din[7] ^ din[8] ^ din[11] ^ din[12] ^ din[16] ^ din[18] ^ din[19] ^ din[20] ^ din[21] ^ din[22];
    assign dout[7] = din[0] ^ din[1] ^ din[3] ^ din[5] ^ din[9] ^ din[12] ^ din[13] ^ din[16] ^ din[17] ^ din[19] ^ din[20] ^ din[22];
    assign dout[8] = din[0] ^ din[1] ^ din[4] ^ din[5] ^ din[6] ^ din[8] ^ din[10] ^ din[13] ^ din[14] ^ din[16] ^ din[17] ^ din[18] ^ din[20];
    assign dout[9] = din[1] ^ din[2] ^ din[5] ^ din[6] ^ din[7] ^ din[9] ^ din[11] ^ din[14] ^ din[15] ^ din[17] ^ din[18] ^ din[19] ^ din[21];
    assign dout[10] = din[2] ^ din[3] ^ din[6] ^ din[7] ^ din[8] ^ din[10] ^ din[12] ^ din[15] ^ din[16] ^ din[18] ^ din[19] ^ din[20] ^ din[22];
    assign dout[11] = din[0] ^ din[2] ^ din[3] ^ din[4] ^ din[5] ^ din[7] ^ din[9] ^ din[11] ^ din[13] ^ din[17] ^ din[19] ^ din[20];
    assign dout[12] = din[1] ^ din[3] ^ din[4] ^ din[5] ^ din[6] ^ din[8] ^ din[10] ^ din[12] ^ din[14] ^ din[18] ^ din[20] ^ din[21];
    assign dout[13] = din[2] ^ din[4] ^ din[5] ^ din[6] ^ din[7] ^ din[9] ^ din[11] ^ din[13] ^ din[15] ^ din[19] ^ din[21] ^ din[22];
    assign dout[14] = din[0] ^ din[2] ^ din[3] ^ din[6] ^ din[7] ^ din[10] ^ din[12] ^ din[14] ^ din[20] ^ din[21] ^ din[22];
    assign dout[15] = din[0] ^ din[1] ^ din[2] ^ din[3] ^ din[4] ^ din[5] ^ din[7] ^ din[11] ^ din[13] ^ din[15] ^ din[16] ^ din[22];
    assign dout[16] = din[0] ^ din[1] ^ din[3] ^ din[4] ^ din[6] ^ din[12] ^ din[14] ^ din[17] ^ din[21];
    assign dout[17] = din[1] ^ din[2] ^ din[4] ^ din[5] ^ din[7] ^ din[13] ^ din[15] ^ din[18] ^ din[22];
    assign dout[18] = din[0] ^ din[3] ^ din[6] ^ din[14] ^ din[19] ^ din[21];
    assign dout[19] = din[1] ^ din[4] ^ din[7] ^ din[15] ^ din[20] ^ din[22];
    assign dout[20] = din[0];
    assign dout[21] = din[1];
    assign dout[22] = din[2];
    assign dout[23] = din[3];
    assign dout[24] = din[4];
    assign dout[25] = din[5];
    assign dout[26] = din[6];
    assign dout[27] = din[7];
    assign dout[28] = din[8];
    assign dout[29] = din[9];
    assign dout[30] = din[10];
    assign dout[31] = din[11];

endmodule