//---------------------------------------------------------------------------------------
// this module is auto generated by prbs_verilog_gen.py
// Generated on: 2025-04-22T09:37:41
// Description: Verilog module for PRBS11 generator,this module is 20 times shift result.
// Polynomial: 1 + x^9 + x^11
// Width: 32
// Iterations: 20
//--------------------------------------------------------------------------------------

module prbs11_width32_iter20 (
    input [31:0] din,
    output [31:0] dout
);

    assign dout[0] = din[2] ^ din[7] ^ din[9];
    assign dout[1] = din[3] ^ din[8] ^ din[10];
    assign dout[2] = din[0] ^ din[4];
    assign dout[3] = din[1] ^ din[5];
    assign dout[4] = din[2] ^ din[6];
    assign dout[5] = din[3] ^ din[7];
    assign dout[6] = din[4] ^ din[8];
    assign dout[7] = din[5] ^ din[9];
    assign dout[8] = din[6] ^ din[10];
    assign dout[9] = din[0] ^ din[7] ^ din[9];
    assign dout[10] = din[1] ^ din[8] ^ din[10];
    assign dout[11] = din[0] ^ din[2];
    assign dout[12] = din[1] ^ din[3];
    assign dout[13] = din[2] ^ din[4];
    assign dout[14] = din[3] ^ din[5];
    assign dout[15] = din[4] ^ din[6];
    assign dout[16] = din[5] ^ din[7];
    assign dout[17] = din[6] ^ din[8];
    assign dout[18] = din[7] ^ din[9];
    assign dout[19] = din[8] ^ din[10];
    assign dout[20] = din[0];
    assign dout[21] = din[1];
    assign dout[22] = din[2];
    assign dout[23] = din[3];
    assign dout[24] = din[4];
    assign dout[25] = din[5];
    assign dout[26] = din[6];
    assign dout[27] = din[7];
    assign dout[28] = din[8];
    assign dout[29] = din[9];
    assign dout[30] = din[10];
    assign dout[31] = din[11];

endmodule